#!/usr/bin/env Rscript

library(methylKit)
library (graphics)
library (tools)

setwd("/home/datawork-ihpe/Pearl_Oyster_Colour_BS_Seq/06_bismark")

load("R.objects/my_meth_all_together_clean_INVERSED.rda")

dat <- data.frame(my_meth_all_together_inversed[[1]]@.Data[[1]], my_meth_all_together_inversed[[1]]@.Data[[4]], my_meth_all_together_inversed[[1]]@.Data[[2]], my_meth_all_together_inversed[[1]]@.Data[[3]])
write.table(dat, file = "1-R-183_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[2]]@.Data[[1]], my_meth_all_together_inversed[[2]]@.Data[[4]], my_meth_all_together_inversed[[2]]@.Data[[2]], my_meth_all_together_inversed[[2]]@.Data[[3]])
write.table(dat, file = "2-R-183_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[3]]@.Data[[1]], my_meth_all_together_inversed[[3]]@.Data[[4]], my_meth_all_together_inversed[[3]]@.Data[[2]], my_meth_all_together_inversed[[3]]@.Data[[3]])
write.table(dat, file = "3-R-183_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[4]]@.Data[[1]], my_meth_all_together_inversed[[4]]@.Data[[4]], my_meth_all_together_inversed[[4]]@.Data[[2]], my_meth_all_together_inversed[[4]]@.Data[[3]])
write.table(dat, file = "1-J-7_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[5]]@.Data[[1]], my_meth_all_together_inversed[[5]]@.Data[[4]], my_meth_all_together_inversed[[5]]@.Data[[2]], my_meth_all_together_inversed[[5]]@.Data[[3]])
write.table(dat, file = "2-J-7_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[6]]@.Data[[1]], my_meth_all_together_inversed[[6]]@.Data[[4]], my_meth_all_together_inversed[[6]]@.Data[[2]], my_meth_all_together_inversed[[6]]@.Data[[3]])
write.table(dat, file = "3-J-7_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[7]]@.Data[[1]], my_meth_all_together_inversed[[7]]@.Data[[4]], my_meth_all_together_inversed[[7]]@.Data[[2]], my_meth_all_together_inversed[[7]]@.Data[[3]])
write.table(dat, file = "1-V-620_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[8]]@.Data[[1]], my_meth_all_together_inversed[[8]]@.Data[[4]], my_meth_all_together_inversed[[8]]@.Data[[2]], my_meth_all_together_inversed[[8]]@.Data[[3]])
write.table(dat, file = "2-V-620_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[9]]@.Data[[1]], my_meth_all_together_inversed[[9]]@.Data[[4]], my_meth_all_together_inversed[[9]]@.Data[[2]], my_meth_all_together_inversed[[9]]@.Data[[3]])
write.table(dat, file = "3-V-620_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[10]]@.Data[[1]], my_meth_all_together_inversed[[10]]@.Data[[4]], my_meth_all_together_inversed[[10]]@.Data[[2]], my_meth_all_together_inversed[[10]]@.Data[[3]])
write.table(dat, file = "1-R-180_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[11]]@.Data[[1]], my_meth_all_together_inversed[[11]]@.Data[[4]], my_meth_all_together_inversed[[11]]@.Data[[2]], my_meth_all_together_inversed[[11]]@.Data[[3]])
write.table(dat, file = "2-R-180_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[12]]@.Data[[1]], my_meth_all_together_inversed[[12]]@.Data[[4]], my_meth_all_together_inversed[[12]]@.Data[[2]], my_meth_all_together_inversed[[12]]@.Data[[3]])
write.table(dat, file = "3-R-180_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[13]]@.Data[[1]], my_meth_all_together_inversed[[13]]@.Data[[4]], my_meth_all_together_inversed[[13]]@.Data[[2]], my_meth_all_together_inversed[[13]]@.Data[[3]])
write.table(dat, file = "1-J-2_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[14]]@.Data[[1]], my_meth_all_together_inversed[[14]]@.Data[[4]], my_meth_all_together_inversed[[14]]@.Data[[2]], my_meth_all_together_inversed[[14]]@.Data[[3]])
write.table(dat, file = "2-J-2_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[15]]@.Data[[1]], my_meth_all_together_inversed[[15]]@.Data[[4]], my_meth_all_together_inversed[[15]]@.Data[[2]], my_meth_all_together_inversed[[15]]@.Data[[3]])
write.table(dat, file = "3-J-2_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[16]]@.Data[[1]], my_meth_all_together_inversed[[16]]@.Data[[4]], my_meth_all_together_inversed[[16]]@.Data[[2]], my_meth_all_together_inversed[[16]]@.Data[[3]])
write.table(dat, file = "1-V-613_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[17]]@.Data[[1]], my_meth_all_together_inversed[[17]]@.Data[[4]], my_meth_all_together_inversed[[17]]@.Data[[2]], my_meth_all_together_inversed[[17]]@.Data[[3]])
write.table(dat, file = "2-V-613_cpg_count.txt")
dat <- data.frame(my_meth_all_together_inversed[[18]]@.Data[[1]], my_meth_all_together_inversed[[18]]@.Data[[4]], my_meth_all_together_inversed[[18]]@.Data[[2]], my_meth_all_together_inversed[[18]]@.Data[[3]])
write.table(dat, file = "3-V-613_cpg_count.txt")
